client:
    token: YourToken  
    accessRole: Staff Team
    linkedRole: Linked

database:
  host: 127.0.0.1
  port: 3306
  username: root
  password: password
  name: unturned    

dev:
  debug: true